### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by theicechol** [theicechol/metamoles#9]
- [x] Complete PubChem client @elliej3 
- [x] Vectorize enzyme class @ymhwang414 
- [x] Integrate RDKit distance @philipjleung 
- [x] Integrate RDKit compound information @theicechol 
- [x] Set up negative data @blasks 
- [x] Pull code into .py file @ymhwang414 
- [x] Clean code
- [x] ML framework (log reg, svm) @elliej3 
- [x] Validation framework
- [x] add unit test for all .py files @ymhwang414 @philipjleung @blasks @elliej3 @theicechol
